{"ops":[{"insert":"El módulo contabilidad_cfdi esta duplicado\n\nse eliminó el módulo de /addons y se dejó el de extra_localization\n\n\n/opt/odoo/odoo/extra_localization/contabilidad_cfdi/models/account_move.py\ncontabilidad_electronica = fields.Boolean('CE', default=True)"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Cambio a "},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"contabilidad_electronica = fields.Boolean('CE')"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Error en \n/opt/odoo/odoo/extra_localization/contabilidad_cfdi/data/res_currency_data.xml\n\" while parsing /opt/odoo/odoo/extra_localization/contabilidad_cfdi/data/res_currency_data.xml:7, near"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"<record id=\"base.EUR\" model=\"res.currency\">"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"            <field name=\"excel_format_cfdi\">_ * #,##0.00_) ;_ * - #,##0.00_) ;_ * \"-\"??_) ;_ @_ </field>"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"        </record>"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"\ncfdi_traslado\ncatalogos_cfdi\n\nError \nCatalogos cfdi\n  raise Exception(_('Module loading %s failed: file %s could not be processed:\\n %s') % (module, fname, warning_msg))"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Exception: Fallo en la carga del módulo catalogos_cfdi: no se pudo procesar el archivo catalogos_cfdi/data/catalogos.clave_unidad.csv:"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Error desconocido durante la importación <class 'AssertionError'>: External ID conflict, catalogos_clave_unidad1 already refers to a `cve.clave.unidad` record, you can't define a `catalogos.clave_unidad` record with this ID."},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Error desconocido durante la importación <class 'AssertionError'>: External ID conflict, catalogos_clave_unidad2 already refers to a `cve.clave.unidad` record, you can't define a `catalogos.clave_unidad` record with this ID."},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Error desconocido durante la importación <class 'AssertionError'>: External ID conflict, catalogos_clave_unidad3 already refers to a `cve.clave.unidad` record, you can't define a `catalogos.clave_unidad` record with this ID."},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Error desconocido durante la importación <class 'AssertionError'>: External ID conflict, catalogos_clave_unidad4 already refers to a `cve.clave.unidad` record, you can't define a `catalogos.clave_unidad` record with this ID."},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Error desconocido durante la importación <class 'AssertionError'>: External ID conflict, catalogos_clave_unidad5 already refers to a `cve.clave.unidad` record, you can't define a `catalogos.clave_unidad` record with this ID."},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Error desconocido durante la importación <class 'AssertionError'>: External ID conflict, catalogos_clave_unidad6 already refers to a `cve.clave.unidad` record, you can't define a `catalogos.clave_unidad` record with this ID."},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Error desconocido durante la importación <class 'AssertionError'>: External ID conflict, catalogos_clave_unidad7 already refers to a `cve.clave.unidad` record, you can't define a `catalogos.clave_unidad` record with this ID."},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Error desconocido durante la importación <class 'AssertionError'>: External ID conflict, catalogos_clave_unidad8 already refers to a `cve.clave.unidad` record, you can't define a `catalogos.clave_unidad` record with this ID."},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Error desconocido durante la importación <class 'AssertionError'>: External ID conflict, catalogos_clave_unidad9 already refers to a `cve.clave.unidad` record, you can't define a `catalogos.clave_unidad` record with this ID."},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Error desconocido durante la importación <class 'AssertionError'>: External ID conflict, catalogos_clave_unidad10 already refers to a `cve.clave.unidad` record, you can't define a `catalogos.clave_unidad` record with this ID."},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Found more than 10 errors and more than one error per 10 records, interrupted to avoid showing too many errors."},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Quitar dejar solo catalogos.clave_unidad.csv en el manifest\nGenera duplicidad de id\nEliminar tabla catalogos_clave_unidad"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"\n\n  File \"/opt/odoo/odoo/odoo/models.py\", line 3164, in write"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"    self._write(old_vals)"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"  File \"/opt/odoo/odoo/odoo/models.py\", line 3335, in _write"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"    self._validate_fields(vals)"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"  File \"/opt/odoo/odoo/odoo/models.py\", line 1061, in _validate_fields"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"    raise ValidationError(\"%s\\n\\n%s\" % (_(\"Error while validating constraint\"), tools.ustr(e)))"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"odoo.exceptions.ValidationError: ('Error mientras se validaban las restricciones\\n\\nEl campo `estado_csd` no existe\\n\\nContexto del error:\\nVista `res.company.form.inherit`\\n[view_id: 1115, xml_id: complemento_exterior.Partner_form, model: res.company, parent_id: 95]', None)"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"\n\n\n2022-03-30 22:03:44,342 1482 ERROR CONTABILIDAD_4G_INGENIERIA_2 odoo.http: Exception during JSON request handling."},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Traceback (most recent call last):"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"  File \"/opt/odoo/odoo/odoo/models.py\", line 1057, in _validate_fields"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"    check(self)"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"  File \"/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py\", line 342, in _check_xml"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"    self.postprocess_and_fields(view.model, view_doc, view.id)"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"  File \"/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py\", line 1083, in postprocess_and_fields"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"    self.raise_view_error(message, view_id)"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"  File \"/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py\", line 533, in raise_view_error"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"    raise ValueError(message)"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"ValueError: El campo `opportunity_id` no existe"},{"attributes":{"code-block":true},"insert":"\n\n"},{"insert":"Contexto del error:"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Vista `sale.order.form.inherit`"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"[view_id: 1067, xml_id: cdfi_invoice.view_sale_order_form_inherit, model: sale.order, parent_id: 736]"},{"attributes":{"code-block":true},"insert":"\n\n"},{"insert":"During handling of the above exception, another exception occurred:"},{"attributes":{"code-block":true},"insert":"\n\n"},{"insert":"\nActualizar /media/odoo-dev/JRMPACHECO/OdooX/odoo/addons/sale_crm/__manifest__.py\n\nagregar al manifest\n/opt/odoo/odoo/extra_localization/escenario_de_ventas/__manifest__.py\n    # any module necessary for this one to work correctly"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"    'depends': ['base','crm','mrp','mail','product','sale_crm'],"},{"attributes":{"code-block":true},"insert":"\n"},{"insert":"Actualiza /opt/odoo/odoo/extra_localization/cdfi_invoice/__manifest__.py\n'sale','account','account_invoicing', 'purchase','sale_crm'"},{"attributes":{"code-block":true},"insert":"\n"}]}